language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

env:
  global:
    - SECRET_KEY=charlesosoti
    - DEBUG=True


script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=api
  - codecov

after_sucess:
  - "codecov"