language: python

python:
  - "3.6"

service:
  - postgresql

before_install:
  - export MODE="testing"
  - export SECRET_KEY="charlesosoti"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

script:
  - python manage.py cov
  - codecov

after_success:
  "codecov"