"""empty message

Revision ID: cac6237b507c
Revises: ed65dddaee4a
Create Date: 2018-05-02 09:54:05.434420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cac6237b507c'
down_revision = 'ed65dddaee4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('meals_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('menus_meal_id_fkey', 'menus', type_='foreignkey')
    op.create_foreign_key(None, 'menus', 'meals', ['meals_id'], ['id'])
    op.drop_column('menus', 'meal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('meal_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.create_foreign_key('menus_meal_id_fkey', 'menus', 'meals', ['meal_id'], ['id'])
    op.drop_column('menus', 'meals_id')
    # ### end Alembic commands ###
